server:
  port: 8099
  servlet:
    context-path: /tqb
spring:
  application:
    name: tqb-service
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
logging:
  level:
    com.dhais.tqb.mapper: debug